[config]
reload_apps = true


[templates.rofi]
input_path = "~/.config/matugen/templates/rofi-colors.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.discord]
input_path = "~/.config/matugen/templates/midnight-discord.css"
output_path = "~/.config/Vencord/themes/midnight-discord.css"


